/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppProspectionHistoryRouteImport } from './routes/_app.prospection-history'
import { Route as AppServiceClientRouteImport } from './routes/_app.service-client'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppFormsIndexRouteImport } from './routes/_app.forms.index'
import { Route as AppFormsIdRouteImport } from './routes/_app.forms.$id'
import { Route as AppProspectsIndexRouteImport } from './routes/_app.prospects.index'
import { Route as AppProspectsIdRouteImport } from './routes/_app.prospects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectionHistoryRoute = AppProspectionHistoryRouteImport.update({
  id: '/prospection-history',
  path: '/prospection-history',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceClientRoute = AppServiceClientRouteImport.update({
  id: '/service-client',
  path: '/service-client',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectsIndexRoute = AppProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectsIdRoute = AppProspectsIdRouteImport.update({
  id: '/prospects/$id',
  path: '/prospects/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/prospection-history': typeof AppProspectionHistoryRoute
  '/service-client': typeof AppServiceClientRoute
  '/services': typeof AppServicesRoute
  '/forms/$id': typeof AppFormsIdRoute
  '/prospects/$id': typeof AppProspectsIdRoute
  '/forms/': typeof AppFormsIndexRoute
  '/prospects/': typeof AppProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/prospection-history': typeof AppProspectionHistoryRoute
  '/service-client': typeof AppServiceClientRoute
  '/services': typeof AppServicesRoute
  '/forms/$id': typeof AppFormsIdRoute
  '/prospects/$id': typeof AppProspectsIdRoute
  '/forms': typeof AppFormsIndexRoute
  '/prospects': typeof AppProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/prospection-history': typeof AppProspectionHistoryRoute
  '/_app/service-client': typeof AppServiceClientRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/forms/$id': typeof AppFormsIdRoute
  '/_app/prospects/$id': typeof AppProspectsIdRoute
  '/_app/forms/': typeof AppFormsIndexRoute
  '/_app/prospects/': typeof AppProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/dashboard'
    | '/knowledge'
    | '/prospection-history'
    | '/service-client'
    | '/services'
    | '/forms/$id'
    | '/prospects/$id'
    | '/forms/'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/dashboard'
    | '/knowledge'
    | '/prospection-history'
    | '/service-client'
    | '/services'
    | '/forms/$id'
    | '/prospects/$id'
    | '/forms'
    | '/prospects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/knowledge'
    | '/_app/prospection-history'
    | '/_app/service-client'
    | '/_app/services'
    | '/_app/forms/$id'
    | '/_app/prospects/$id'
    | '/_app/forms/'
    | '/_app/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospection-history': {
      id: '/_app/prospection-history'
      path: '/prospection-history'
      fullPath: '/prospection-history'
      preLoaderRoute: typeof AppProspectionHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service-client': {
      id: '/_app/service-client'
      path: '/service-client'
      fullPath: '/service-client'
      preLoaderRoute: typeof AppServiceClientRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/': {
      id: '/_app/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/$id': {
      id: '/_app/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospects/': {
      id: '/_app/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof AppProspectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospects/$id': {
      id: '/_app/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof AppProspectsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConversationsRoute: typeof AppConversationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppProspectionHistoryRoute: typeof AppProspectionHistoryRoute
  AppServiceClientRoute: typeof AppServiceClientRoute
  AppServicesRoute: typeof AppServicesRoute
  AppFormsIdRoute: typeof AppFormsIdRoute
  AppProspectsIdRoute: typeof AppProspectsIdRoute
  AppFormsIndexRoute: typeof AppFormsIndexRoute
  AppProspectsIndexRoute: typeof AppProspectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConversationsRoute: AppConversationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppProspectionHistoryRoute: AppProspectionHistoryRoute,
  AppServiceClientRoute: AppServiceClientRoute,
  AppServicesRoute: AppServicesRoute,
  AppFormsIdRoute: AppFormsIdRoute,
  AppProspectsIdRoute: AppProspectsIdRoute,
  AppFormsIndexRoute: AppFormsIndexRoute,
  AppProspectsIndexRoute: AppProspectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
