/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEmailRouteImport } from './routes/_app.email'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppQuoteGeneratorRouteImport } from './routes/_app.quote-generator'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as FCodeRouteImport } from './routes/f.$code'
import { Route as AppFormsIndexRouteImport } from './routes/_app.forms.index'
import { Route as AppFormsIdRouteImport } from './routes/_app.forms.$id'
import { Route as AppProspectsIndexRouteImport } from './routes/_app.prospects.index'
import { Route as AppProspectsIdRouteImport } from './routes/_app.prospects.$id'
import { Route as AppQuotesIndexRouteImport } from './routes/_app.quotes.index'
import { Route as AppQuotesIdRouteImport } from './routes/_app.quotes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppQuoteGeneratorRoute = AppQuoteGeneratorRouteImport.update({
  id: '/quote-generator',
  path: '/quote-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const FCodeRoute = FCodeRouteImport.update({
  id: '/f/$code',
  path: '/f/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectsIndexRoute = AppProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectsIdRoute = AppProspectsIdRouteImport.update({
  id: '/prospects/$id',
  path: '/prospects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIdRoute = AppQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/email': typeof AppEmailRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/notifications': typeof AppNotificationsRoute
  '/quote-generator': typeof AppQuoteGeneratorRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/f/$code': typeof FCodeRoute
  '/forms/$id': typeof AppFormsIdRoute
  '/prospects/$id': typeof AppProspectsIdRoute
  '/quotes/$id': typeof AppQuotesIdRoute
  '/forms/': typeof AppFormsIndexRoute
  '/prospects/': typeof AppProspectsIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/email': typeof AppEmailRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/notifications': typeof AppNotificationsRoute
  '/quote-generator': typeof AppQuoteGeneratorRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/f/$code': typeof FCodeRoute
  '/forms/$id': typeof AppFormsIdRoute
  '/prospects/$id': typeof AppProspectsIdRoute
  '/quotes/$id': typeof AppQuotesIdRoute
  '/forms': typeof AppFormsIndexRoute
  '/prospects': typeof AppProspectsIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/email': typeof AppEmailRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/quote-generator': typeof AppQuoteGeneratorRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/f/$code': typeof FCodeRoute
  '/_app/forms/$id': typeof AppFormsIdRoute
  '/_app/prospects/$id': typeof AppProspectsIdRoute
  '/_app/quotes/$id': typeof AppQuotesIdRoute
  '/_app/forms/': typeof AppFormsIndexRoute
  '/_app/prospects/': typeof AppProspectsIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/email'
    | '/knowledge'
    | '/notifications'
    | '/quote-generator'
    | '/services'
    | '/settings'
    | '/f/$code'
    | '/forms/$id'
    | '/prospects/$id'
    | '/quotes/$id'
    | '/forms/'
    | '/prospects/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/email'
    | '/knowledge'
    | '/notifications'
    | '/quote-generator'
    | '/services'
    | '/settings'
    | '/f/$code'
    | '/forms/$id'
    | '/prospects/$id'
    | '/quotes/$id'
    | '/forms'
    | '/prospects'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/email'
    | '/_app/knowledge'
    | '/_app/notifications'
    | '/_app/quote-generator'
    | '/_app/services'
    | '/_app/settings'
    | '/f/$code'
    | '/_app/forms/$id'
    | '/_app/prospects/$id'
    | '/_app/quotes/$id'
    | '/_app/forms/'
    | '/_app/prospects/'
    | '/_app/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FCodeRoute: typeof FCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email': {
      id: '/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quote-generator': {
      id: '/_app/quote-generator'
      path: '/quote-generator'
      fullPath: '/quote-generator'
      preLoaderRoute: typeof AppQuoteGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/f/$code': {
      id: '/f/$code'
      path: '/f/$code'
      fullPath: '/f/$code'
      preLoaderRoute: typeof FCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/forms/': {
      id: '/_app/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms/$id': {
      id: '/_app/forms/$id'
      path: '/forms/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospects/': {
      id: '/_app/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof AppProspectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospects/$id': {
      id: '/_app/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof AppProspectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$id': {
      id: '/_app/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AppQuotesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailRoute: typeof AppEmailRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppQuoteGeneratorRoute: typeof AppQuoteGeneratorRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppFormsIdRoute: typeof AppFormsIdRoute
  AppProspectsIdRoute: typeof AppProspectsIdRoute
  AppQuotesIdRoute: typeof AppQuotesIdRoute
  AppFormsIndexRoute: typeof AppFormsIndexRoute
  AppProspectsIndexRoute: typeof AppProspectsIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmailRoute: AppEmailRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppQuoteGeneratorRoute: AppQuoteGeneratorRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppFormsIdRoute: AppFormsIdRoute,
  AppProspectsIdRoute: AppProspectsIdRoute,
  AppQuotesIdRoute: AppQuotesIdRoute,
  AppFormsIndexRoute: AppFormsIndexRoute,
  AppProspectsIndexRoute: AppProspectsIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FCodeRoute: FCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
