/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppConversationsRouteImport } from './routes/_app.conversations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppServiceClientRouteImport } from './routes/_app.service-client'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceClientRoute = AppServiceClientRouteImport.update({
  id: '/service-client',
  path: '/service-client',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/service-client': typeof AppServiceClientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/service-client': typeof AppServiceClientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/service-client': typeof AppServiceClientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/conversations' | '/dashboard' | '/knowledge' | '/service-client'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conversations' | '/dashboard' | '/knowledge' | '/service-client'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/knowledge'
    | '/_app/service-client'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service-client': {
      id: '/_app/service-client'
      path: '/service-client'
      fullPath: '/service-client'
      preLoaderRoute: typeof AppServiceClientRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConversationsRoute: typeof AppConversationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppServiceClientRoute: typeof AppServiceClientRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConversationsRoute: AppConversationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppServiceClientRoute: AppServiceClientRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
